const r = require('express').Router();
const c = require('../controllers/fileController');
const { requireAuth } = require('../middleware/auth');
const { upload } = require('../middleware/upload');
r.use(requireAuth);
r.get('/', c.listDir);
r.get('/search', c.searchFiles);
r.get('/stats', c.storageStats);
r.get('/recycle', c.getRecycleBin);
r.get('/:id', c.getNode);
r.post('/folder', c.createFolder);
r.post('/text', c.createTextFile);
r.post('/upload', upload.single('file'), c.uploadFile);
r.put('/:id/content', c.updateContent);
r.put('/:id/rename', c.renameNode);
r.put('/:id/move', c.moveNode);
r.put('/recycle/:id/restore', c.restoreNode);
r.delete('/recycle/empty', c.emptyRecycleBin);
r.delete('/:id', c.softDelete);
module.exports = r;
